version: '3'
services:
  todofront:
    build: ./todo-app/front-end
    expose:
      - 3000
    depends_on:
      - backend
    environment:
      - REACT_APP_API_HOST: todoback
  todoback:
    build: ./todo-app/back-end
    expose:
      - 3001
  todotests:
    build: ./todo-app/tests
    depends_on:
      - todofront
      - backend
    environment:
      - FRONT_HOST: todofront